language: elixir
elixir:
- 1.4.0
deploy:
  provider: heroku
  api_key:
    secure: fZD6lGjbrs3F85r/RfADxZqN/93iKxtiB5zyMVn/hEdkUqnqTLL1N94ijxBG8Bdi+TOOFG1E/3SuIYR2CMe3GIu7X/9eC8QxMZGvORBBobImhiq7OAA5wwKfXVj1fLAnU3dbu2z7cf9j2wjHck9lELOaiZow1onVUv/Yk+U8DzlylvbiXb8mvztl0r0Y6pDDO0IaXhjZBKaVlZ5+ciJcsMSg+6VU/ypWAr/6Td51TwnJu1OEz1B8+c6HatPRT16LIXyROVU6B8NxSG9nH3i2VcmYHeLT3+i/Ak43K+4wVLbVjQoEQ+kLNUqw/g6JtIIxpx24nw2KBre7UvkVhK2xB2RKcatcKQP3mKvR0JCcciosV5zo/uJwWgFSfYRNUt7tidjeWfYUhIYRpAlaWAu8bORLtojfIS5dB5SQcLLi0Wm0+8bZijTzRhKDy3hGKKoBdzOHltnRhH4Y2o2Ch1A7BFdLpE3qAfH0HfGY+B8lWPrSro+DoHeQhJZGpRTXAPeZ2Ezlevby7pPzJkaZ4tQ5SAfnNQs7pf1L55vgAVZBWL6KVerx8x+0iGDN2RQ2vQ/H330b1TjGNe7x3sZ1kGTPQ6L+8RwapE7LtmKnQqeLPq9zqc9XoOP44UxtgaTKb3jkAZGV1AAhKuAwbihUlWTITYEVp4ue+jxPfhMvHvhUrVc=
  app: phtt
  on:
    repo: codingricky/judgement
