language: elixir
elixir:
- 1.4.0

deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJJDQBTHUQYJPLG3Q
  secret_access_key:
      secure: lSsSe8kIwSBFuya5i9qEpkA1nvi0toyQK9T5m4lZCli9ix30R0tvLRQaltiAbjZcOg6avHkFqfkz8gzqdQOf6/XplK3XsL51yX6xt7IhDA2bdssI3ocNjEthdPrLRcYwpq1NaE4nEnaEai3096YwM+4H39BXXJWSs+h/+5592ndzDhNjIzGU7l3bYulqYR6DZ8X4dw8BH44gX+Oe0PwbUDZHz1M6xfR4BPB6dqgfPZY1oM4TXHyRBT6oNqsdV7/fUedHUoTGSiWjyx5MWw/bOfkUbZlBaDhlqNDRrkxThFGDh4ahknSG22X2nhKbAcS2DbRV1ERF4F8XFhds8jRahxSSMgbE233yjg9VI3EXOt0SiYZ9zJC1xhiri13Ra8/MK3n1F93wvK2GGP1sgrDLmYGSkxO2Uw5FpROFU2MviVl2rT322jJdMGQUKdLJyEl0l2op1Dc4ajqJ8RHvEK9w2yQTv+ENFDB8Avk2Ht6qAliFpSwj+Y5VBCiD20bdPHGQGT/WpNw0zN8yq1fVmp220PVtaNsI9211pQ+RdTuf39nl3Os34e6qEwl2yKxSxI1mx3Sbo3MrJAGtGxkttiiH4L1IJRTLHVWfm7csH3oPDt5IT7Rj/VhNOwf83VEcLgln263D/0kQzqR8M/Q4mP4eNvKpw9lr6ZfvCndGG5QmHoc=
  region: ap-southeast-2
  app: another-dius-table-tennis-app
  env: dtt-dev
  bucket_name: rickys-builds
  on:
    repo: codingricky/judgement
    branch: production