language: elixir
elixir:
- 1.5.0
deploy:
  provider: s3
  access_key_id: AKIAJKQURCT6VL3SVY6Q
  secret_access_key:
    secure: QQrsZLVA8dypGtjwOTHJMkFRlohPCGT9LiIjqrTwRniQpFj/aA2RqL1GEF544etk3PZT8hVqL/BsOLuPLYn5avUPu+y3BhGjJauiTE3CQs+N8P/fkVTJu1c2LMj2H7koqT8JsvWPpiPLG80sDhAOhenpjOtgbYZDtrtGK9DvbGzbPqADPwAoDn530EMvw+f2NmBGiG4WKeXC56zxdPaFky80cD8f1a80H6iW2ZyBZPIWT5rdGR02qIpRbJoNqyaQA6iPNQGusbgVpNZm9d/2mldxM85ByrBWG5gFq7n8LXLJF4dTy+psSAQfh6XXKEaawoKkGj8ztrGcx8SbSi2MtVxAJ+WWuKAKrmrzy/cSXAqzqdoSDQ6smF60ZKfyE8OyuXOXR/Oc24Fd81ue8SbWAOZ0r/Rgf/VbjK3yqtJ7krhmnVrPnZnyl8+4lvNOQ9mwiM1nioPJm9R1AZTfJqiKcf1s5iySuAhHN8IQpfKehl9XsWk2IVUS9OBKjyFX0S7G+aWGsThwbg0FiLhA0cyb0G6E7V+yDkKPQPWpUa08ACKB00uqKNUnF5OoQ8zB3Bx1b/TpCbgyRS72u9zrj8WeOJVrKZcglmrlgCXtYb1dTiPVy2aypyftx/OEFOoUXToUDTGeSEM1h7s/fIwcrxwXmjOj7xCDlHGMO1oFJWvGS8Y=
  bucket: rickys-builds
  on:
    repo: codingricky/judgement
    branch: production
  provider: heroku
  api_key:
      secure: "SGxLxuYbYuJxSzfPWx6UznsMRF3hyq/WODWdYAqpjQOGSEcPeJdmcvDePjDHtf0MemrGj7jxXfnDH81cWT+Ct0s7txb4F5w+V/hDaMg5TZLchOYnC/J3Hk5Mqrl/16kccYGqoeCwSUha3zzaEq+XEOpgY0LcBoSHqcilA5yuhZ7bISC37ycLDvWQ3mqtG0KIgcRBgLtZjZVe4ZhPQF9at6yKC8AQI2ZgbGH+0AL3SstCLBx27WIvxEpuFLdd02JwzoqaSdr9corVayTPU3+eI0KZXh8azlLj2ZpJmUB9YlVLpOAVLbQwLpOkwhVVG9UiUp3DwzrWziE4URFKomoWfL0O8e3QpUad7thLk8rYfTo4GFt5zL7O5lnyenG+eLC93GlJyGzr6HWoKGKmTcDhmwLs9ocodJFmuzMtwc3w+oj3Lgg6VPRQ6LSkZO5pGLcS+hFeHn9iISG1sdfAFSXB33/XE6jCMJo6PPWxqCefowBpnJ1evUjlx5eKWwRKU0MuNEsQBxYJDabZgmYiEGjyIZJ9tTE8Lu2aFYHnaZU0ct9vWsCjPdN3xBRv/ZWS63A0rNZy1RmW6C5ms48pj9OGBNoyFEPR+kWdzQXX6ZRNv9xnDgzMEQbPxA8MfgDOYaR23ga6RwW9M6enriVjizag9rpkHOdBp43B6rdagV0IiYE="
  app: phtt
on:
    repo: codingricky/judgement
    branch: master