language: elixir
elixir:
- 1.4.0
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIA7NAO7BROR35NAA
  secret_access_key:
    secure: "lRSYJ0wHdzN/YJRO4sTbxSPYIVHKq05gjZfDttZtTd/v3IojS91ZrJcIUwGNvW1X00El3sDh87q4NOkCWbGE3WMQMQ2JzFnIIyH4wzclX4dG4NwYdnm8rxn/RwYFWJfKEG7ELbT8JNqCn0h+mIU9rxIcrQq6k9/wzk9Z1I8wFu9QSpwC/y3SSFVRA3TEb1DjVh0QH0FYz1lqEnboHDaKSSDhXs4cB6ihj77vww3DaFVwjMdV9uoGHFgAt0lm2+2qfPPuIhru58OM+K2dD4qxPseLD6I/vOJk+5EUtgaCM7MmNtgbJcj+C3c2PQtAqIRQqJjnYKhTCdeKfygjGHHbvQlsUokfMCRVaVnYODwR3462qIph8QKgvru3VLDF4tlyLg2IiU580w8GZet8xUBmUxJQGtaRaddOWuqVB8FxJ/oQzDyKFE8eMRravoqX9hBGvF3eV6VqZwnEDwDa/zqqomJ3XrrMWXotoazjiLeqVTZnGsZOu5K1rlpB9QbSVegNpoWsliPAcfzG2uvQ+4BXejKIAMfKqIbkhLf2rvRvVJEak34qggAj4RZoPGNhCANxM3+DaxKGWGFBqVeVxVxkbIZQ9cyiWX3Ct5Vyx6Ikcf2Pc19JY2KgWf782X2ccHm7AGb/DBfGnt7Xl9aNBgU2D3RuxvZlsAGwGXKprN1z0To="  region: ap-southeast-2
  app: another-dius-table-tennis-app
  env: dtt-dev
  bucket_name: rickys-builds
  on:
    repo: codingricky/judgement
    branch: production
