language: elixir
elixir:
- 1.4.0
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJKQURCT6VL3SVY6Q
  secret_access_key:
  secure: "RJnDdwqQeyrRGQ5pSJMrGvD99VM+7cg6lTwjVt7Le2U2SfLCke+P6UP0tdb78OPpCfmBSHSsB8rEc1d7lXa5lgCqdyI8WuSYfWGHEG3f/9LV0rIGMudmp/7JNiM9saUZd4+6YXXh+JCyJRWw+goN7FI1VDQTAOOjs/VqEYEGwCs7DCD7i2jdz9ZlXyNZ4q1YqPJZh/ZxpJHsKoEt6enlxozn2fbvGrmznBropZEMOfA/rK2uibf/sNb8S3ZVDm2UKBYQ5aFsLF1eNsxHjOy1XT3E10t27AkydFIMeY+2FENcfi1RRq5huhYau9kZnVWSxpglkQu51WCg9dqPugH9O0A2kenZ3NmdEx2v6BZ5uIiCPUxeoqUxy+sGJJWJtmnBrX2R8sX5UB6BUCwOIPRnkMtY76iomYhKLCr9jPGNIcSowcsewjkGE+dj/Zu3di/SY9VjafBf9ycjtiorqHby+OTiW9DCN3P7wEN4tqBxAPyyQHNq/SVpLbetYSD22bQBgN1rPw38yjaRW2+gk56p5frniBqg1thBXc2qA/rJPGWa7Gmo78ADzMydJLzAMUxxGS0GwTpydPhjr96gZBf03qthGuzvjEsz5v2xMo6a0AgzFpjrk0Oav/eJYAQfDkUbhfE5GLT94Ks23FHTWuEZhdhX+nskc6m+VX5GK0lXLYI="
    region: ap-southeast-2
  app: another-dius-table-tennis-app
  env: dtt-dev
  bucket_name: rickys-builds
  on:
    repo: codingricky/judgement
    branch: production
