language: elixir
elixir:
- 1.4.0
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJKQURCT6VL3SVY6Q
  secret_access_key:
    secure: "imx1Lo/1WWi9opqP2J4Rmr1WFfH/0JX4/Fo8Lw5cgjooHkc9gV336cQPrffKxgab+tUJGLZ5mlA/gYaQverg+EMjehWiSRh3qaD/ECdIXtntoTvw7jqoopzbyhFp2gYdk9xQy9vQmaNlEFvIDTJkAcDXvxmqUMXjv+2n4Qq1Iz+l1Gdt8Xni6Q0tegFzoEKQQWBzhjVbaxYDYEWMdIUatpAZYzqu2sSHyHnUWtSLRlKKREwVFsrnQkBcz67btkpXHVqgK9LkMTpSGFwS3DTthpAalFhxbHUdDEpOO4m76v8cwgHp5g0Jd4j+FwkIU9XxjA09+7kLCkDLu0azTHAYVkqEhSbG435ZaNaTbtWfwpQuVt4mlFZUvcHbLVyJ5GSAKzZiTqg4GqJFUXICjiGYo1ptsAnp5kBaet4RdcIxPlSk2AjYt7tmcmNVxVZ/+VUoKGJOIoVwwQpppCYvkD2CNIzEHa3ywWNmnVgTZ9wwijgDkOFKgClqgruQaI7+/bQeP8pW4gPhNjD/3tZCEC6Q4EDEZdIc+atQl7gdNG9tKNmd8HKQVXnWRB5pisoxNDJdhdAmT+7KPquSYF997E7FSEZ2HfjTfHbGyPgviVVmiqG9MTrDVeNCDK4+OMNFhgqxRmBLqqepW+kLuAVzPGNnsA+S6xigNDelFTdFyRyhnws="  
  region: ap-southeast-2
  app: another-dius-table-tennis-app
  env: dtt-dev
  bucket_name: rickys-builds
  on:
    repo: codingricky/judgement
    branch: production
