language: elixir
elixir:
- 1.4.1
deploy:
  provider: s3
  access_key_id: AKIAJKQURCT6VL3SVY6Q
  secret_access_key:
    secure: QQrsZLVA8dypGtjwOTHJMkFRlohPCGT9LiIjqrTwRniQpFj/aA2RqL1GEF544etk3PZT8hVqL/BsOLuPLYn5avUPu+y3BhGjJauiTE3CQs+N8P/fkVTJu1c2LMj2H7koqT8JsvWPpiPLG80sDhAOhenpjOtgbYZDtrtGK9DvbGzbPqADPwAoDn530EMvw+f2NmBGiG4WKeXC56zxdPaFky80cD8f1a80H6iW2ZyBZPIWT5rdGR02qIpRbJoNqyaQA6iPNQGusbgVpNZm9d/2mldxM85ByrBWG5gFq7n8LXLJF4dTy+psSAQfh6XXKEaawoKkGj8ztrGcx8SbSi2MtVxAJ+WWuKAKrmrzy/cSXAqzqdoSDQ6smF60ZKfyE8OyuXOXR/Oc24Fd81ue8SbWAOZ0r/Rgf/VbjK3yqtJ7krhmnVrPnZnyl8+4lvNOQ9mwiM1nioPJm9R1AZTfJqiKcf1s5iySuAhHN8IQpfKehl9XsWk2IVUS9OBKjyFX0S7G+aWGsThwbg0FiLhA0cyb0G6E7V+yDkKPQPWpUa08ACKB00uqKNUnF5OoQ8zB3Bx1b/TpCbgyRS72u9zrj8WeOJVrKZcglmrlgCXtYb1dTiPVy2aypyftx/OEFOoUXToUDTGeSEM1h7s/fIwcrxwXmjOj7xCDlHGMO1oFJWvGS8Y=
  bucket: rickys-builds
  on:
    repo: codingricky/judgement
    branch: production
  provider: heroku
  api_key:
      secure: "FMf54mbAIADV5UZEXjg5NQToY4F9lcX3MXG+e5NUUqqFX4Fv08cQrw3K0WTuEWFW9jB0TolaunquzED1H2Rqki+WB9ISdUW46nfO5wbb0mNyLmMrDaSNn1lDtikYttDIM0IjMBEpuqJqUh2E8mNBT3T+DuY7sLUOjlCDr7NcEJCqz5JdPoDdRzvIcfVhZZQ09fqiapKHtOxQtnZ5RPwldZgOFoA+l8bHT8gJDd9VUoH4tFPe59ttLBSFIIveOX44/iQE3JR7XZefInOjQJQjpLNg1iUYsTJfLxHFZmMW5nuQP4ZquAQ9Wc++E2a6rK1MxxBpVNqyr7lhQC0PHqGXPkbCe65cNcIKniGbtmkdGQ+DjI1kVZmJlxvRaoSH+nvtoO87dL3/8p22d690ZLW7SZFDRU5Sp1TnhIOCHjtcsnmAd0mkTywQT12iajEDR6jQuL1SabXqw/F+BRSacJmGEf702VPERxA8GpPLEGW1s4/ACc1m8F6568adYqu4yFzIB1+/JvsmSU9TV9mArQGmf3z85lKt64cCAGbHxA8Q2rh1SiKPXVtCnFTb5tzI/2B1GiGkRmChTarJQ64gA9hzVLuqKv3PydU87tUFi7wDhDMs0JXwi8EaKLqfBmlCvH03S4H8RZFkMCjGHiY7CtQo8hKcLT9NX0196pnIvMkwnOA="
  app: phtt
  on:
    repo: codingricky/judgement
    branch: master